apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    workschedule.example.com/policy: ny-work-hours
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        image: nginx:1.21
        ports:
        - containerPort: 80