apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: workschedules.example.com

spec:
  group: example.com
  scope: Cluster
  names:
    plural: workschedules
    singular: workschedule
    kind: WorkSchedule
    shortNames:
    - ws  

  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - startTime
              - endTime
              properties:
                startTime:
                  type: string
                  pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$'
                  description: "Start time for the pod to be active, in HH:MM format."
                endTime:
                  type: string
                  pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$'
                  description: "End time for the pod to be active, in HH:MM format."
                timeZone:
                  type: string
                  description: "Time zone for the start and end times, in IANA Time Zone Database format. Defaults to UTC."
                  default: "Etc/UTC"
                  pattern: '^[A-Za-z]+/[A-Za-z_]+$'
      additionalPrinterColumns:
        - name: "Start-Time"
          type: "string"
          jsonPath: ".spec.startTime"
        - name: "End-Time"
          type: "string"
          jsonPath: ".spec.endTime"
        - name: "Time-Zone"
          type: "string"
          jsonPath: ".spec.timeZone"

